# Generated by Django 5.1.3 on 2025-02-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_line_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoofPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.JSONField()),
                ('tilt_angle', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bottom_edge_index', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoofEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.JSONField()),
                ('is_bottom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='solar.roofpolygon')),
            ],
        ),
        migrations.DeleteModel(
            name='Line',
        ),
    ]
