# Generated by Django 5.1.3 on 2025-02-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0004_project_roofpolygon_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
    ]
