# Generated by Django 5.1.3 on 2025-03-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0005_remove_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='roofpolygon',
            name='height_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
