# Generated by Django 5.1.3 on 2025-03-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0007_jsonify_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roofpolygon',
            name='project',
        ),
        migrations.RemoveField(
            model_name='roofedge',
            name='polygon',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='RoofEdge',
        ),
        migrations.DeleteModel(
            name='RoofPolygon',
        ),
    ]
