# Generated by Django 5.1.3 on 2025-03-21 15:03

from django.db import migrations

def set_null_user(apps, schema_editor):
    SolarProject = apps.get_model('solar', 'SolarProject')
    for project in SolarProject.objects.all():
        project.user = None
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0010_userprofile_alter_solarproject_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(set_null_user),
    ]