# Generated by Django 5.1.3 on 2025-03-21 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0011_set_null_for_existing_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('width', models.FloatField(help_text='Panel width in meters')),
                ('height', models.FloatField(help_text='Panel height in meters')),
                ('thickness', models.FloatField(help_text='Panel thickness in meters')),
                ('wattage', models.FloatField(help_text='Peak power in watts')),
                ('efficiency', models.FloatField(help_text='Efficiency percentage')),
                ('cost', models.FloatField(help_text='Cost per panel in euros')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panels', to='solar.panelmanufacturer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solar_panels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
